print('What do you get when you cross a snowman with a vampire')
input()
print('Frosbite!')
print()

print('What do dentists call a astrounaut\' cavity?')
input()
print('A black hole!')
print()

print('Know know?')
input()
print("Who's there?")
input()
print('Interrupting cow')
input()
print('Interrupting cow wh', end='')
print('-MOO!')
